pinterp: /users/hgarsden/anaconda3_herasim/bin/python
run_as_batch: True
mem: 232                # GB
repetitions: 4
run_time: "48:00:00"
gpu_run_time: "18:00:00"
show_output: False
short_run:
        enable: False
        run_time: "1:00:00"
        gpu_run_time: "1:00:00"
        mem: 1          # GB

#run_these: [ "hera_sim_cpu_az", "hera_sim_cpu_astropy", "hera_sim_cpu_az_update", "hera_sim_cpu_beam_pix", "hera_sim_gpu", "pyuvsim", "healvis" ]

run_these: [ "hera_sim_cpu_az_update" ]

# Parameter definitions

defaults:
  antennas: 5
  channels: 20
  sources: 20
  times: 20

antennas:
    max: 350
    step: 25

channels:
    max: 1000
    step: 50
    
sources:
    max: 10000
    step: 500

times:
    max: 1000
    step:  50


# Simulation definitions

hera_sim_cpu_az:
        script: hera_sim_sim.py        
        title: hera_sim CPU az

hera_sim_cpu_astropy:
        script: hera_sim_sim.py
        option: use_astropy
        title: hera_sim CPU astropy

hera_sim_cpu_az_update:
        script: hera_sim_sim.py
        option: use_az_fix
        title: hera_sim CPU az update

hera_sim_cpu_beam_pix:
        script: hera_sim_sim.py
        option: use_beam_pix
        title: hera_sim CPU beam pix

hera_sim_gpu:
        script: hera_sim_sim.py
        option: use_gpu
        title: hera_sim GPU

pyuvsim:
        script: pyuvsim_sim.py
        title: pyuvsim
        nproc: 32

healvis:
        script: healvis_sim.py
        title: healvis

